### ISSUE TITLE
Typescript not working for replayNormalized

### ISSUE THREAD

**Issue by cderche** [tardis-dev/tardis-node#22]
Hi - I am using typescript with [tsdx](https://tsdx.io), a zero-config CLI for TypeScript package development.

I have re-created the basic [replayNormalized](https://docs.tardis.dev/api/node-js#replaynormalized-options-normalizers) example from the documentation.

For some reason, the function is continuously returning `undefined` instead of the message. Any best guesses as to why?

```ts
// single.ts
import { replayNormalized, normalizeTrades, ReplayNormalizedOptions } from 'tardis-dev'

const messages = replayNormalized(
  {
    exchange: 'bitmex',
    symbols: ['XBTUSD'],
    from: '2019-05-01',
    to: '2019-05-02'
  } as ReplayNormalizedOptions<'bitmex'>,
  normalizeTrades
)

async function run () {
  for await (const message of messages) {
    console.log(message);
  }
}

run()
```

**Comment by thaaddeus** [comment]
Hi, I've just tried it in TypeScript, works perfectly fine, whole lib is actually developed in TS, I don't have much experience with tsdx unfortunately, which version of TS does it use under the hood?

**Comment by cderche** [comment]
Thanks @thaaddeus for looking into it. It seems this is a tsdx issue https://github.com/formium/tsdx/pull/795.
