### ISSUE TITLE
kucoin support

### ISSUE THREAD

**Issue by kigorw** [tardis-dev/tardis-node#23]
hi, any plans for kucoin?

**Comment by ComguitoTT** [comment]
any update? roadmap said Kucoin for December 2021

**Comment by thaaddeus** [comment]
it should be integrated by the end of January.

**Comment by p-i-** [comment]
🚀
When it is integrated, will it ONLY be serving data from end of Jan, or have you been stockpiliing some?

**Comment by thaaddeus** [comment]
added in v13.6.0
