### ISSUE TITLE
Suggestion: cache mechanism improvement

### ISSUE THREAD

**Issue by hackape** [tardis-dev/tardis-node#25]
Currently the historical data feed API accept a composite `filters` param, and cache is stored in:

`feeds/${exchange}/${sha256(filters)}/`

However from my experience working with the lib, mostly I just pick one exchange one symbol, then depending on scenario, I add or drop channels frequently.

Current cache mechanism will basically invalidate cache when I add channels, since the sha256 hash changes. It's not very economic. `tardis-machine` caches in same fashion so does not change the situation.

### Suggestion

I think it might be better if data caches are stored in `feeds/${payload.exchange}/${symbol}/${channel}/`, when cache hit, we read multiple streams then merge them back into one single stream.

The gain is quite obvious, higher cache hit rate means less waiting time, also less bandwidth/traffic for server side, less disk usage. Trade-off is some computation overhead on client side.

The drawback here is that it introduce a new problem: how to decide the emission order of messages.

I'm willing to write the code, but I don't have any knowledge of how emission order is decided within the datafeed server. So if you like my suggestion, can you please share some insight on this part?

**Comment by thaaddeus** [comment]
Agree about upsides, as you pointed out, tricky part here would be merging messages from 'partial' caches (files). Server does not decide on the order, it filters out from larger set to smaller one, and larger set (full feed) is recorded in the same order as exchange published messages.
In practice, local timestamp can be used to reconstruct that order.

It would be very nice addition to have, but it's not so straightforward to implement. If you'd want to give it as shoot, please add it behind option flag passed to `replay` fn.

**Comment by hackape** [comment]
> If you'd want to give it as shoot, please add it behind option flag passed to replay fn.

Yeah, that's also my thought. If implemented it should be opt-in.

> In practice, local timestamp can be used to reconstruct that order.

That I can see. Do you suggest local timestamp for one single exchange is unique to each message?

How is the "larger set" store in server, is it stored in database then filtered by a SQL query?

**Comment by thaaddeus** [comment]
I think local timestamp should be unique enough (it's 100ns precision), not sure if in practice exchange was publishing more than one message in such short 100ns interval, but I guess it should be good enough for use case where you need to merge different channels files... but yeah it may not give 100% the same order as an API (two messages with the same timestamp in theory as possible). Server side storage and filtering is all custom made, not using SQL db.
