### ISSUE TITLE
close ws connection on demand

### ISSUE THREAD

**Issue by evgenyfedorenko** [tardis-dev/tardis-node#30]
Hi,

Is there a way to close the connection for real time orderbook updates?

Thanks.

**Comment by thaaddeus** [comment]
Yes, you need to break/end the `for await` loop.

**Comment by evgenyfedorenko** [comment]
also if I try to create a stream for already streamed ticker - will it create a dupe connection?

**Comment by thaaddeus** [comment]
yes, each `streamNormalized` maintains separate connection.

**Comment by evgenyfedorenko** [comment]
Thanks!
