### ISSUE TITLE
Throw an error when ticker not found

### ISSUE THREAD

**Issue by evgenyfedorenko** [tardis-dev/tardis-node#31]
Hi.

Currently if ticker is incorrect and it is used in `streamNormalized` there will no indication of incorrect ticker.
Is there a way to know that the connection was not established for the given ticker?

**Comment by thaaddeus** [comment]
Right now, best way is to use https://github.com/tardis-dev/tardis-node/blob/master/src/exchangedetails.ts#L5 and see which symbols are available and then use those or validate using those.

**Comment by evgenyfedorenko** [comment]
Got it, thanks
