### ISSUE TITLE
connections to external http(s) and ws endpoints do not work when running behind a corporate proxy

### ISSUE THREAD

**Issue by rakeshkaria** [tardis-dev/tardis-node#32]
#### Summary
`tardis-node` does not work when running on a machine that sits behind a corporate proxy.

#### Detail
`tardis-machine` uses `tardis-node` in order to manage websocket and http(s) connections to exchanges. If you try to run up a `tardis-machine` instance behind a corporate proxy, outbound requests to exchange http(s) and ws endpoints will fail; and no messages will be returned. These connections are constructed (and destroyed) in `tardis-node`.

#### Example:
Running this test (taken from `tardismachine.test.ts`):

```
test(
      'subcribes to and replays historical BitMEX data feed of 1st of Jun 2019 (XBTUSD trades and  orderBookL2 updates)',
      async () => {        
        const startTimestamp = new Date().getTime()
        let messagesCount = 0
        let lastBitmexMessage

        const simpleBitmexWSClient = new SimpleWebsocketClient(
          `${WS_REPLAY_URL}?exchange=bitmex&from=2019-06-01&to=2019-06-02`,
          (message) => {            
            messagesCount++
            lastBitmexMessage = message
          },
          () => {
            simpleBitmexWSClient.send({
              op: 'subscribe',
              args: ['trade:XBTUSD', 'orderBookL2:XBTUSD']
            })
          }
        )

        await simpleBitmexWSClient.closed()
        console.log(`WS received  for BitMEX ${messagesCount} in ${(new Date().getTime() - startTimestamp) / 1000} seconds`)
        expect(lastBitmexMessage).toMatchSnapshot()
        expect(messagesCount).toBe(7690673)
      },
      10 * 60 * 1000
    )
```

Fails, as no messages are fetched.

If you amend the code in `tardis-node` such that all connections are provided details of the appropriate proxy server, the tests pass.

#### Attempted workarounds
I tried using `global-agent` to inject the proxy into all requests without needing to modify the source code, but have been unable to make this work.

#### Proposed fix
Please can the connections being made from within `tardis-node` be updated so that either:

1. the system proxy - as defined by `http_proxy` or `https_proxy` (Linux), or `HTTP_PROXY` or `HTTPS_PROXY` (Windows) - is honoured; or
2. a proxy can be supplied at point of initialisation, via a commandline option.

As far as I can tell, there are three places where an external connection is created, and where configuration of a proxy may be required:

1. `handy.ts` inside `async function _downloadFile`;
2. `realtimefeeds/realtimefeeds.ts` inside `async *_stream`
3. `exchangedetails.ts` inside `getExchangeDetails`.

**Comment by thaaddeus** [comment]
Thanks, is there a chance you can provide pull request for that improvement?

**Comment by rakeshkaria** [comment]
Thanks for the reply. I've submitted one here: https://github.com/tardis-dev/tardis-node/pull/33.
Note that an additional change will be required to `tardis-machine` such that the new option can be fed through appropriately. I will happily create a PR for this too.
