### ISSUE TITLE
Handling similar live data points for same timestamp

### ISSUE THREAD

**Issue by onebrunchman** [tardis-dev/tardis-node#34]
This is regarding `streamNormalized` function in which we are getting the live data for various symbols from various exchanges.

Certain exchanges like FTX are returning the timestamp down to the microseconds precision while other exchanges only return timestamp down to milliseconds:
```javascript
{
  type: 'trade',
  symbol: 'ADA-PERP',
  exchange: 'ftx',
  id: '1595962600',
  price: 1.8778,
  amount: 333,
  side: 'buy',
  timestamp: 2021-08-13T02:30:54.289Z { 'μs': 554 },
  localTimestamp: 2021-08-13T02:30:54.869Z
}
```

```javascript
{
  type: 'trade',
  symbol: 'BTC/USDT',
  exchange: 'ascendex',
  id: undefined,
  price: 44996.57,
  amount: 0.003,
  side: 'sell',
  timestamp: 2021-08-13T02:35:04.052Z,
  localTimestamp: 2021-08-13T02:35:04.931Z
}
```

With the microseconds timestamp, it is highly unlikely to receive 2 or more transactions with exactly the same data within the same microseconds (same data as in same price, amount, side, exchange, symbol, type, and timestamp). It is different for milliseconds however. 

If live data is being used to store in a database like InfluxDB, points with similar timestamps will be overwritten (https://docs.influxdata.com/influxdb/v2.0/write-data/best-practices/duplicate-points/). This would result in the data being inaccurate. 

For example:
Trade A: 
```javascript
{
  type: 'trade',
  symbol: 'BTC/USDT',
  exchange: 'ascendex',
  id: undefined,
  price: 44996.57,
  amount: 0.003,
  side: 'sell',
  timestamp: 2021-08-13T02:35:04.052Z,
  localTimestamp: 2021-08-13T02:35:04.931Z
}
```

Trade B: 
```javascript
{
  type: 'trade',
  symbol: 'BTC/USDT',
  exchange: 'ascendex',
  id: undefined,
  price: 44996.57,
  amount: 0.003,
  side: 'sell',
  timestamp: 2021-08-13T02:35:04.052Z,
  localTimestamp: 2021-08-13T02:35:04.931Z
}
```

The 2 trades above should result in the following being saved into the database (note the **amount: 0.006**):
```javascript
{
  type: 'trade',
  symbol: 'BTC/USDT',
  exchange: 'ascendex',
  id: undefined,
  price: 44996.57,
  amount: 0.006,
  side: 'sell',
  timestamp: 2021-08-13T02:35:04.052Z,
  localTimestamp: 2021-08-13T02:35:04.931Z
}
```

As you might have noticed, a unique identifier is required to be able to differentiate between duplicate trades or a different trade but with exact same data. Some exchanges are returning `id` while others like `ascendex` doesn't.

So how should this be handled to ensure data will be accurate. Also, this would apply to liquidations data as well.

**Comment by thaaddeus** [comment]
Hi, unfortunately it's hard to handle it on the lib level. Perhaps in your code you could check if trade.id is undefined and if it is, then generate unique identifier for it (GUID for example).
