### ISSUE TITLE
How do I point to a Tardis Machine?

### ISSUE THREAD

**Issue by samcrane8** [tardis-dev/tardis-node#36]
Hey I'd like to use this client but I can't currently see how to point to the tardis machine I host. I specifically am looking to grab pricing data from a websocket. Any guidance would be appreciated.

**Comment by thaaddeus** [comment]
With tardis-node client you don't need to use tardis-machine, as tardis-machine is built-on top of it, you can simply replay/stream the data using the client, docs are at https://github.com/tardis-dev/tardis-node
