### ISSUE TITLE
Wrong funding rates for FTX (Historical API - replayNormalized)

### ISSUE THREAD

**Issue by grayfox-basis** [tardis-dev/tardis-node#37]
Hello everyone!

**Goal:** I am using tardis-node to **collect historical funding rates** for `derivative_ticker` LTC-PERP for every hour @FTX exchange.

**Problem:** Funding rates fluctuate and are not equal to the ones reported in: https://ftx.com/funding.

**Example:**

1. Let's consider we want **LTC-PERP** for **FTX** funding rates for the **last 2 days**. Using a simple configuration like:
  ```js
  replayPayload {
    exchange: 'ftx',
    symbols: [ 'LTC-PERP' ],
    from: '2022-01-17T04:00:00.000Z',
    to: '2022-01-18T18:43:56.752Z'
  }
  ```
2. Let's establish some ground truth from `ftx.com/funding` and isolate our LTC-PERP. We get the following funding rate values:
![ftx_gt](https://user-images.githubusercontent.com/97624790/150003322-62b3f12c-d354-4843-acf6-b4e535f560b9.png)
3. Now I want to replicate the results above using WS historical API, so I create the pipeline and await for incoming messages:
```js
    let messages = replayNormalized(
        replayPayload, normalizeTrades, normalizeDerivativeTickers
    );

    messages = compute(
        messages,
        computeTradeBars({
          kind: 'time',
          interval: 1 * 60 * 60 * 1000,
        })
    );
    
    for await (let message of wsStream) {
       // process - messages with type == 'derivative_ticker'
    }
```
4. I start to get a stream of messages, as expected, with the form:
```js
msg:  {
  type: 'derivative_ticker',
  symbol: 'LTC-PERP',
  exchange: 'ftx',
  lastPrice: 152.32,
  openInterest: 276799.87,
  fundingRate: -0.00005,
  fundingTimestamp: 2022-01-17T11:00:00.000Z,
  predictedFundingRate: undefined,
  indexPrice: 152.1622,
  markPrice: 152.27,
  timestamp: 2022-01-17T10:01:14.864Z { 'μs': 291 },
  localTimestamp: 2022-01-17T10:01:14.864Z { 'μs': 291 }
}
```
5. Looking into the stream of messages for the last messages sent during the last minutes of "Jan 17 2022 10:00:00" and the first minutes of "Jan 17 2022 11:00:00" for the `fundingTimestamp` (fts) of "Jan 17 2022 11:00:00", there are 2 different funding rates... `0.000006` and `0.000007`.
![Screenshot 2022-01-18 at 19 22 17](https://user-images.githubusercontent.com/97624790/150005258-cbb74329-a808-4d3c-9dcd-c7b938817f79.png)
6. As we noticed in Point 2, the correct funding rate is not the last rate sent (0.000006) but the one that comes before.

**My issue is**  that I need funding rates to be precise with the ones in FTX.com and I keep getting wrong results after trying the following methodologies:
1. I consider the `fundingRate` of the message with the highest `timestamp` for a group of `fundingTimestamps` with same values.
    Example: for `Jan 17 2020 11:00:00` I consider the message with `timestamp` `11:00:49`.
2. I consider the `fundingRate` of the message with the highest `timestamp` just before the `fundingTimestamp`.
    Example: for `Jan 17 2020 11:00:00` I consider the message with `timestamp` `10:59:44`.
3. I consider the `fundingRate` of the message with the highest `timestamp` just after the `fundingTimestamp`.
    Example: for `Jan 17 2020 11:00:00` I consider the message with `timestamp` `11:00:00`.

For the case study presented above, neither of the 3 methods would return me the correct funding rate of 0.000007.

Am I doing something wrong? Is this situation expected? How do I get a 1to1 mapping with the ftx.com/funding data?

**Comment by cryptoboole** [comment]
Amen, this is one of the most troublesome aspects of using this awesome repo. There is no normalised "this is the reported value"...

**Comment by andreasBasis** [comment]
this should definitely be looked at

**Comment by thaaddeus** [comment]
Hi,
I'll start with info how funding rate data is sourced from FTX as it's unfortunately not available via WS feed, so it's done by pooling that info every 4-6 seconds from https://docs.ftx.com/#get-future-stats API - nextFundingRate field.
Derivative ticker is meant to always provide info about funding rate for closest funding event not funding event that already happened hence this API endpoint was used.
Funding rate value is not modified in any way so what you get is what FTX API provided.

I'd also want to point that dates on https://ftx.com/funding are localised so best to compare with API responses from https://docs.ftx.com/#get-funding-rates.

I can see some mismatches but it was reported like that by their API response, don't know why sometimes there are those small differences observed.

I found one issue that was fixed (sometimes FTX API was returning stale funding info - could be some caching not sure, but it's handled now in latest release).

Here's values I get for tardis & ftx historical funding API:
```json
{
  "2022-01-17T00:00:00.000Z": {
    "tardisDataRate": -0.000001,
    "ftxRate": -0.000001
  },
  "2022-01-17T01:00:00.000Z": {
    "tardisDataRate": 0.000002,
    "ftxRate": 0.000002
  },
  "2022-01-17T02:00:00.000Z": {
    "tardisDataRate": 0.000005,
    "ftxRate": 0.000005
  },
  "2022-01-17T03:00:00.000Z": {
    "tardisDataRate": 0.000012,
    "ftxRate": 0.000012
  },
  "2022-01-17T04:00:00.000Z": {
    "tardisDataRate": 0.000004,
    "ftxRate": 0.000004
  },
  "2022-01-17T05:00:00.000Z": {
    "tardisDataRate": 0.000006,
    "ftxRate": 0.000006
  },
  "2022-01-17T06:00:00.000Z": {
    "tardisDataRate": 0.000007,
    "ftxRate": 0.000007
  },
  "2022-01-17T07:00:00.000Z": {
    "tardisDataRate": 0.000002,
    "ftxRate": 0.000002
  },
  "2022-01-17T08:00:00.000Z": {
    "tardisDataRate": 0,
    "ftxRate": 0
  },
  "2022-01-17T09:00:00.000Z": {
    "tardisDataRate": 0.00001,
    "ftxRate": 0.00001
  },
  "2022-01-17T10:00:00.000Z": {
    "tardisDataRate": 0.000005,
    "ftxRate": 0.000005
  },
  "2022-01-17T11:00:00.000Z": {
    "tardisDataRate": 0.000006, // no match
    "ftxRate": 0.000007
  },
  "2022-01-17T12:00:00.000Z": {
    "tardisDataRate": 0,
    "ftxRate": 0
  },
  "2022-01-17T13:00:00.000Z": {
    "tardisDataRate": 0.00001,
    "ftxRate": 0.00001
  },
  "2022-01-17T14:00:00.000Z": {
    "tardisDataRate": 0.000006,
    "ftxRate": 0.000006
  },
  "2022-01-17T15:00:00.000Z": {
    "tardisDataRate": 0, // no match
    "ftxRate": 0.000001
  },
  "2022-01-17T16:00:00.000Z": {
    "tardisDataRate": 0.000004,
    "ftxRate": 0.000004
  },
  "2022-01-17T17:00:00.000Z": {
    "tardisDataRate": 0.000005,
    "ftxRate": 0.000005
  },
  "2022-01-17T18:00:00.000Z": {
    "tardisDataRate": 0.000002,
    "ftxRate": 0.000002
  },
  "2022-01-17T19:00:00.000Z": {
    "tardisDataRate": 0.000009,
    "ftxRate": 0.000009
  },
  "2022-01-17T20:00:00.000Z": {
    "tardisDataRate": 0.000011,
    "ftxRate": 0.000011
  },
  "2022-01-17T21:00:00.000Z": {
    "tardisDataRate": 0,
    "ftxRate": 0
  },
  "2022-01-17T22:00:00.000Z": {
    "tardisDataRate": 0.000004,
    "ftxRate": 0.000004
  },
  "2022-01-17T23:00:00.000Z": {
    "tardisDataRate": 0.000015,
    "ftxRate": 0.000015
  },
  "2022-01-18T00:00:00.000Z": {
    "tardisDataRate": 0.000013, // no match
    "ftxRate": 0.000012
  },
  "2022-01-18T01:00:00.000Z": {
    "tardisDataRate": 0.000006,
    "ftxRate": 0.000006
  },
  "2022-01-18T02:00:00.000Z": {
    "tardisDataRate": -0.000002,
    "ftxRate": -0.000002
  },
  "2022-01-18T03:00:00.000Z": {
    "tardisDataRate": -0.000001,
    "ftxRate": -0.000001
  },
  "2022-01-18T04:00:00.000Z": {
    "tardisDataRate": -0.000006,
    "ftxRate": -0.000006
  },
  "2022-01-18T05:00:00.000Z": {
    "tardisDataRate": -0.000003,
    "ftxRate": -0.000003
  },
  "2022-01-18T06:00:00.000Z": {
    "tardisDataRate": -0.000003,
    "ftxRate": -0.000003
  },
  "2022-01-18T07:00:00.000Z": {
    "tardisDataRate": 0.000007,
    "ftxRate": 0.000007
  },
  "2022-01-18T08:00:00.000Z": {
    "tardisDataRate": -0.000003,
    "ftxRate": -0.000003
  },
  "2022-01-18T09:00:00.000Z": {
    "tardisDataRate": -0.000009,
    "ftxRate": -0.000009
  },
  "2022-01-18T10:00:00.000Z": {
    "tardisDataRate": -0.000008,
    "ftxRate": -0.000008
  },
  "2022-01-18T11:00:00.000Z": {
    "tardisDataRate": -0.000012,
    "ftxRate": -0.000011
  },
  "2022-01-18T12:00:00.000Z": {
    "tardisDataRate": -0.000003,
    "ftxRate": -0.000003
  },
  "2022-01-18T13:00:00.000Z": {
    "tardisDataRate": -0.00001,
    "ftxRate": -0.00001
  },
  "2022-01-18T14:00:00.000Z": {
    "tardisDataRate": -0.000015,
    "ftxRate": -0.000015
  },
  "2022-01-18T15:00:00.000Z": {
    "tardisDataRate": -0.000009, // no match
    "ftxRate": -0.00001
  },
  "2022-01-18T16:00:00.000Z": {
    "tardisDataRate": -0.000012,
    "ftxRate": -0.000012
  },
  "2022-01-18T17:00:00.000Z": {
    "tardisDataRate": -0.000003,
    "ftxRate": -0.000003
  },
  "2022-01-18T18:00:00.000Z": {
    "tardisDataRate": -0.000012,
    "ftxRate": -0.000012
  },
  "2022-01-18T19:00:00.000Z": {
    "tardisDataRate": -0.000002,
    "ftxRate": -0.000002
  },
  "2022-01-18T20:00:00.000Z": {
    "tardisDataRate": -0.000001,
    "ftxRate": -0.000001
  },
  "2022-01-18T21:00:00.000Z": {
    "tardisDataRate": -0.000007,
    "ftxRate": -0.000007
  },
  "2022-01-18T22:00:00.000Z": {
    "tardisDataRate": 0.000003,
    "ftxRate": 0.000002
  },
  "2022-01-18T23:00:00.000Z": {
    "tardisDataRate": -0.000005,
    "ftxRate": -0.000005
  },
  "2022-01-19T00:00:00.000Z": {
    "tardisDataRate": -0.000018,
    "ftxRate": -0.000018
  },
  "2022-01-19T01:00:00.000Z": {
    "tardisDataRate": -0.000005,
    "ftxRate": -0.000005
  },
  "2022-01-19T02:00:00.000Z": {
    "tardisDataRate": -0.00001,
    "ftxRate": -0.00001
  },
  "2022-01-19T03:00:00.000Z": {
    "tardisDataRate": -0.000016, // no match
    "ftxRate": -0.000017
  },
  "2022-01-19T04:00:00.000Z": {
    "tardisDataRate": -0.000015,
    "ftxRate": -0.000015
  },
  "2022-01-19T05:00:00.000Z": {
    "tardisDataRate": -0.000006,
    "ftxRate": -0.000006
  },
  "2022-01-19T06:00:00.000Z": {
    "tardisDataRate": -0.000004,
    "ftxRate": -0.000004
  },
  "2022-01-19T07:00:00.000Z": {
    "tardisDataRate": -0.000003,
    "ftxRate": -0.000003
  },
  "2022-01-19T08:00:00.000Z": {
    "tardisDataRate": -0.000004,
    "ftxRate": -0.000004
  }
}
```




Here's script I used to check that:
```js
const { replayNormalized, normalizeDerivativeTickers } = require('tardis-dev')
const fetch = require('got')

let messages = replayNormalized(
  {
    exchange: 'ftx',
    symbols: ['LTC-PERP'],
    from: '2022-01-17T00:00:00.000Z',
    to: '2022-01-19T08:20:00.000Z',
    apiKey: 'YOUR API KEY'
  },

  normalizeDerivativeTickers
)

let lastFundingInfo
const tardisFunding = {}

async function run() {
  for await (let message of messages) {
    if (message.type === 'derivative_ticker') {
      if (lastFundingInfo !== undefined && lastFundingInfo.fundingTimestamp.toISOString() !== message.fundingTimestamp.toISOString()) {
        tardisFunding[lastFundingInfo.fundingTimestamp.toISOString()] = {
          tardisDataRate: lastFundingInfo.fundingRate
        }
      }
      lastFundingInfo = message
    }
  }

  const ftxFundingRatesResponse = fetch(`https://ftx.com/api/funding_rates?future=LTC-PERP`)

  const ftxFundingRates = await ftxFundingRatesResponse.json()
  // console.log(ftxFundingRates)

  for (const key in tardisFunding) {
    const matchingFtxFundingRate = ftxFundingRates.result.find((f) => new Date(f.time).toISOString() === key)
    if (!matchingFtxFundingRate) {
      console.log('not found', key)
    }

    tardisFunding[key].ftxRate = matchingFtxFundingRate.rate
  }

  console.log(JSON.stringify(tardisFunding, null, 2))
}

run()

```

**Comment by grayfox-basis** [comment]
Any intentions of providing `nextFundingRate` and `fundingRate` in separate properties in the future? Like ones would come from https://docs.ftx.com/#get-future-stats and another from https://docs.ftx.com/#get-funding-rates.

Anyway thank you very much for the quick answer (with examples) and all the details you provided.

**Comment by thaaddeus** [comment]
No plans at least right now, that would require support for all exchanges not only FTX and it's a complex task, I'll try to ask FTX support about that issue - they also had plans to provide that info over WS which perhaps would help.

**Comment by grayfox-basis** [comment]
I will close the issue and implement a connector just for the **ftx** and see if it works!

Thank you for the clarity and for being so helpful!

**Comment by thaaddeus** [comment]
Sure, no problem, if you'll figure out how to handle it properly please let me know I'll see what I can do regarding supporting it both for historical and real-time data, thanks!
