### ISSUE TITLE
Can't get exchange details

### ISSUE THREAD

**Issue by airon-tark** [tardis-dev/tardis-node#40]
Have this version

    "tardis-dev": "^13.1.7"

Doing like that

    import {getExchangeDetails, replay} from "tardis-dev";

    const details = await getExchangeDetails('binance')
    console.log(details)

it shows me

    error: RequestError: connect ECONNREFUSED 127.0.0.1:443

My connection is good

    % ping tardis.dev

    PING tardis.dev (104.26.15.246): 56 data bytes
    64 bytes from 104.26.15.246: icmp_seq=0 ttl=54 time=84.853 ms
    64 bytes from 104.26.15.246: icmp_seq=1 ttl=54 time=86.738 ms
    64 bytes from 104.26.15.246: icmp_seq=2 ttl=54 time=84.799 ms
    64 bytes from 104.26.15.246: icmp_seq=3 ttl=54 time=84.899 ms
    64 bytes from 104.26.15.246: icmp_seq=4 ttl=54 time=85.816 ms

**Comment by thaaddeus** [comment]
Hi, please see https://runkit.com/thad/get-exchange-details - seems to be working fine, same locally for me.
Also those endpoints are monitored from multiple geo locations and there were no downtimes for those at all.
Did you by any chance have some proxy configured or smth similar?

**Comment by airon-tark** [comment]
@thaaddeus thanks for the answer
will retest and let you know
