### ISSUE TITLE
DYDX historical funding rates not matching

### ISSUE THREAD

**Issue by grayfox-basis** [tardis-dev/tardis-node#41]
Hello everyone!

I have been noticing that the tardis reported funding rates for DYDX are a bit off when compared to their historical ground truth.

* My funding rates:
<img width="495" alt="Screenshot 2022-02-01 at 16 02 57" src="https://user-images.githubusercontent.com/97624790/152004314-00b7fa8e-3be4-4816-bb55-70bc6a11f0e5.png">
* Their funding rates (go to fundings tab): https://trade.dydx.exchange/trade/YFI-USD

Code to replicate:
```js
import _ from 'lodash';
import {
  compute,
  computeTradeBars,
  normalizeTrades,
  replayNormalized,
  normalizeDerivativeTickers
} from 'tardis-dev';
// import * as fetch from 'got';

const { TARDIS_KEY } = process.env;
if (!process.env['TARDIS_KEY']) {
  throw new Error('provide TARDIS_KEY environment variable');
}

let opts = {
  exchange: 'dydx',
  symbols: [
    'YFI-USD'
  ],
  from: '2022-02-01T14:30:00.000Z',
  to: '2022-02-01T15:30:00.000Z',
  apiKey: TARDIS_KEY
};
console.log(_.omit(opts, ['apiKey']));

let messages = replayNormalized(
  opts, normalizeTrades, normalizeDerivativeTickers
);
messages = compute(
  messages,
  computeTradeBars({
    kind: 'time',
    interval: 1 * 60 * 60 * 1000,
  })
);

let lastFundingInfo;
let tardisFunding = {}

async function run() {
  const batch = {};

  console.log('⚠️ start!');
  for await (const item of messages) {
    if (item.type == 'derivative_ticker') {
      if (item.fundingTimestamp) batch[item.fundingTimestamp] = item;
    }
  }
  console.log(batch);
}

run()
```

Thank you again!

**Comment by thaaddeus** [comment]
Hi, this is mentioned in https://docs.tardis.dev/historical-data-details/dydx 
"
nextFundingRate published via v3_markets channel does not exactly matching up with the funding rates that dydx end up paying for open positions, it's also something dYdX team is aware of and working on a fix.
"
TBH I'm not sure what is exactly the issue, but the data is sourced from their markets data feed with not modifications.

**Comment by grayfox-basis** [comment]
Thanks for your reply! closing.
