### ISSUE TITLE
null open_interest value in derivative_ticker message

### ISSUE THREAD

**Issue by thangng48** [tardis-dev/tardis-node#42]
I know to construct **derivative_ticker** messages for some exchanges (binance-futures, ftx, huobi, ...), the library needs to combine websocket streams and http API pooling. Let's talk about `binance-futures` from now. The `open_interest` value is updated every 30s via http API, other fields are based on real-time websocket stream.
That leads to _behavior_ which is 2 normalized `derivative_ticker` streams can get different `open_interest` value.

When normalizing part, if any websocket was disconnected the normalization mapper will be reset

https://github.com/tardis-dev/tardis-node/blob/f1e0a52ebc76e58c50b348f574a27d06de180c94/src/handy.ts#L99

```js
for await (const messageWithTimestamp of messages) {
    if (messageWithTimestamp === undefined) {
      // we received undefined meaning Websocket disconnection
      // lets create new mappers with clean state for 'new connection'
      mappersForExchange = undefined
```

This will lead to a **problem** that websocket was disconnected, the `open_interest` value will be reset to `null`. I think you're saving data to your data warehouse by running the script that's using  **streamNormalized** method also, so there's cause that your historical `derivative_ticker` data contains `null` `open_interest` value.

For instance, as I check with our `tardis-machine`

```curl
curl -g 'http://localhost:8000/replay-normalized?options={"exchange":"binance-futures","from":"2022-02-08T09:15:00","to":"2022-02-08T09:30:00","symbols":["BTCUSDT"],"withDisconnectMessages":false,"dataTypes":["derivative_ticker"]}' | grep -v openInterest
```

```json
{"type":"derivative_ticker","symbol":"BTCUSDT","exchange":"binance-futures","fundingRate":0.0001,"fundingTimestamp":"2022-02-08T16:00:00.000Z","indexPrice":43572.84234988,"markPrice":43569.0714637,"timestamp":"2022-02-08T09:15:00.003Z","localTimestamp":"2022-02-08T09:15:00.060102Z"}
{"type":"derivative_ticker","symbol":"BTCUSDT","exchange":"binance-futures","lastPrice":43581.99,"fundingRate":0.0001,"fundingTimestamp":"2022-02-08T16:00:00.000Z","indexPrice":43572.84234988,"markPrice":43569.0714637,"timestamp":"2022-02-08T09:15:00.464Z","localTimestamp":"2022-02-08T09:15:00.495692Z"}
{"type":"derivative_ticker","symbol":"BTCUSDT","exchange":"binance-futures","lastPrice":43581.99,"fundingRate":0.0001,"fundingTimestamp":"2022-02-08T16:00:00.000Z","indexPrice":43572.84234988,"markPrice":43576.51865716,"timestamp":"2022-02-08T09:15:01.001Z","localTimestamp":"2022-02-08T09:15:01.045776Z"}
{"type":"derivative_ticker","symbol":"BTCUSDT","exchange":"binance-futures","lastPrice":43588,"fundingRate":0.0001,"fundingTimestamp":"2022-02-08T16:00:00.000Z","indexPrice":43572.84234988,"markPrice":43576.51865716,"timestamp":"2022-02-08T09:15:01.470Z","localTimestamp":"2022-02-08T09:15:01.484841Z"}
{"type":"derivative_ticker","symbol":"BTCUSDT","exchange":"binance-futures","lastPrice":43588.01,"fundingRate":0.0001,"fundingTimestamp":"2022-02-08T16:00:00.000Z","indexPrice":43572.84234988,"markPrice":43576.51865716,"timestamp":"2022-02-08T09:15:01.965Z","localTimestamp":"2022-02-08T09:15:01.985901Z"}
```
I think this makes your historical data and other running stream (when getting disconnected)  are not quite accurate.

**Question/Suggestion**:  Is it better to handle the mapper resetting somehow keeping the pooling based way values ?

**Comment by thaaddeus** [comment]
Hi, for our backend we don't use tardis-dev lib actually.
I don't see it inaccurate, just bit less convenient due to  binance requiring using different sources to construct final deriv ticker data message. It's being queried also just after starting connection so empty value is only temporary.
If that's an issue I think one can remember last value and restore it in client code if required.
