### ISSUE TITLE
How to stop stream

### ISSUE THREAD

**Issue by helvenk** [tardis-dev/tardis-node#43]
As the example codes:
```js
const { stream } = require('tardis-dev')

const messages = stream({
  exchange: 'bitmex',
  filters: [
    { channel: 'trade', symbols: ['XBTUSD'] },
    { channel: 'orderBookL2', symbols: ['XBTUSD'] }
  ]
})

for await (const message of messages) {
  console.log(message)
}
```

If my machine cannot connect to `bitmex` server for some reason, websocket would retry connecting all the time under the hood, and the `for await` statement would be stuck.   

Is there any way to stop the retring?

What the **more important** thing is, with `tardis-machine`, even the client was disconnected from  my machine，reatime feeds are still retring to connect to the exchange server.   

How to avoid this problem?

**Comment by thaaddeus** [comment]
For example you could add withDisconnects flag https://github.com/tardis-dev/tardis-node/blob/master/src/stream.ts#L128 and count those disconnects (your message would be undefined then if disconnect happen) if there are too many in small time window you can break the loop.
OR smth like in tardis-machine https://github.com/tardis-dev/tardis-machine/blob/master/src/ws/streamnormalized.ts#L28 and it's onError handler which btw should not retry when client is disconnected - at least in the latest version.

**Comment by helvenk** [comment]
Sorry that I haven't noticed the `tardis-machine` has a limit of 50 times to end the client connection，so the problem I meet  above is not a real problem.  But the magic number should be configurable I suggest。I'll close this issue later. 

Thanks for your reply and thanks your great work.
