### ISSUE TITLE
Batch processing all or nothing

### ISSUE THREAD

**Issue by RobinDeBaets** [tardis-dev/tardis-node#44]
https://github.com/tardis-dev/tardis-node/blob/122a49f9bbb6f6917929a9da25f50d8bc3ed842e/src/realtimefeeds/binance.ts#L42-L48

A bunch of places in the real time feeds use this pattern where `Promise.all` is used to process a whole batch at once.
This is not ideal however, because `Promise.all` will immediately fail as soon as one of its promises fails. A single failed HTTP call will thus invalidate the rest.

A better solution would be to use [Promise.allSettled](https://javascript.info/promise-api#promise-allsettled), which does not have this behaviour.

**Comment by thaaddeus** [comment]
handled in v13.6.0
