### ISSUE TITLE
[question] streamNormalized with zero timeoutIntervalMS

### ISSUE THREAD

**Issue by kovetskiy** [tardis-dev/tardis-node#48]
Hello there, we are extensively using tardis-node in our project, some of exchanges have low number of trades per a period of time on specific assets.

We use https://docs.tardis.dev/api/node-js#stream-normalized-options to get this data, and we see that it is getting disconnected every 10 seconds because of `timeoutIntervalMS`. I've double checked the exchange, and I can see that the assets we are following get traded like once per hour. 

We are considering setting timeoutIntervalMS to zero to avoid this function get called: https://github.com/tardis-dev/tardis-node/blob/fffde11ff0c67380b5af5565d0af867828f9ba07/src/realtimefeeds/realtimefeed.ts#L228 which terminates the connection if no packets were received during this timeoutIntervalMS time: https://github.com/tardis-dev/tardis-node/blob/fffde11ff0c67380b5af5565d0af867828f9ba07/src/realtimefeeds/realtimefeed.ts#L245

Do you think this is a good idea? Would it lead to other problems?

**Comment by thaaddeus** [comment]
should be fine, but could also lead to stale connection (open but inactive WS connection), it's not very common but this is what this mechanism was for.
